# -*- coding: utf-8 -*-
"""data_preparation+exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zov-XomEF-fOYcKMuLwhArOMGh_EHtyC

# Part 2: Feature Extraction and Data Engineering
The raw data was downloaded from the sites of: [MIT](https://www.ll.mit.edu/r-d/datasets/vpnnonvpn-network-application-traffic-dataset-vnat), a premier engineering university, and the [University of New Brunswick (UNB)](https://www.unb.ca//cic/datasets/vpn.html), a leading cybersecurity research hub.

In this phase of the project, we process raw Network Packet Capture (`.pcap`) files into structured Datasets (`.csv`).

Because network traffic is continuous, we use a technique called **Time-Windowing**. We slice the traffic into discrete 15-second chunks. This allows the Machine Learning model to evaluate the "rhythm" of the traffic (e.g., bursts of packets followed by pauses) over a fixed interval, making the data uniform and learnable.

### The Extracted Features (Data Dictionary)
For every 15-second flow, we extract the following mathematical features:
* **Connection Details:** `src_ip`, `dst_ip`, `src_port`, `dst_port`, `protocol` (TCP/UDP).
* **Time Metrics:** `start_time`, `end_time`, `duration` (Length of the time-window).
* **Volume Metrics:**
  * `fwd_pkts`, `bwd_pkts`: Total packets sent forward and backward.
  * `fwd_bytes`, `bwd_bytes`: Total data volume sent forward and backward.
  * `tot_pkts`, `tot_bytes`: Total combined packets and bytes for the entire flow.
* **Symmetry & Ratio Metrics:**
  * `byte_ratio`: The proportion of uploaded vs. downloaded bytes (Crucial for separating asymmetric streaming from symmetric downloads).
  * `pkt_ratio`: The proportion of forward vs. backward packets.
* **Averages (Rates & Sizes):**
  * `avg_pkts_per_sec`, `avg_bytes_per_sec`: The average transmission speed.
  * `avg_fwd_pkt_size`, `avg_bwd_pkt_size`, `avg_pkt_size`: The mean size of the packets in the flow.
* **Timing (Inter-Arrival Time - IAT):**
  * `fwd_iat_mean`, `bwd_iat_mean`: Average time between packets.
  * `fwd_iat_max`, `bwd_iat_max`: The longest pause between packets (crucial for identifying video buffering).
* **TCP Flags:** `fwd_syn`, `fwd_fin`, `bwd_syn`, `bwd_fin` (Used to track connection setups and teardowns).
"""

from google.colab import drive
drive.mount('/content/drive')

# ==============================================================================
# Feature Extraction Lab: PCAP/PCAPNG to CSV Time-Window Chunker (FINAL OPTIMIZED)
# ==============================================================================
import os
import pandas as pd
import numpy as np
try:
    from scapy.all import PcapReader, IP, TCP, UDP
except ImportError:
    import sys
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "scapy"])
    from scapy.all import PcapReader, IP, TCP, UDP
import time

# --- 1. CONFIGURATION ---
PCAP_FOLDERS = [
    "/content/drive/MyDrive/Colab_Notebooks/pcaps/MIT",
    "/content/drive/MyDrive/Colab_Notebooks/pcaps/UNB"
]
CSV_OUTPUT_DIR = "/content/drive/MyDrive/Colab_Notebooks/pcaps/converted_CSVs"

CHUNK_WINDOW_SEC = 15.0  # Size of the time-window
IDLE_TIMEOUT_SEC = 30.0  # Drop flows that are silent for 30 seconds to clear RAM

# --- NEW: EXCLUSION FILTER ---
# Removed 'scp' and 'sftp' so File Transfers are kept!
EXCLUDE_KEYWORDS = ["ssh", "telnet", "rdp", "vnc", "remote"]

os.makedirs(CSV_OUTPUT_DIR, exist_ok=True)

# --- 2. CORE FEATURE EXTRACTION FUNCTION ---
def extract_flow_features(flow_id, flow_data):
    """
    Computes statistical and volumetric features for a given time-window of traffic.
    Includes advanced symmetry metrics (byte_ratio, pkt_ratio).
    """
    src_ip, dst_ip, src_port, dst_port, protocol = flow_id

    fwd_lengths = flow_data['fwd_pkt_lengths']
    bwd_lengths = flow_data['bwd_pkt_lengths']
    all_lengths = fwd_lengths + bwd_lengths

    fwd_iats = flow_data['fwd_iats']
    bwd_iats = flow_data['bwd_iats']

    duration = flow_data['last_seen'] - flow_data['start_time']
    if duration <= 0: duration = 0.000001 # Prevent division by zero safely

    fwd_pkts = len(fwd_lengths)
    bwd_pkts = len(bwd_lengths)
    fwd_bytes = sum(fwd_lengths)
    bwd_bytes = sum(bwd_lengths)
    total_pkts = fwd_pkts + bwd_pkts
    total_bytes = fwd_bytes + bwd_bytes

    # Mathematical Ratios (The Silver Bullets for Tree Models)
    pkt_ratio = fwd_pkts / bwd_pkts if bwd_pkts > 0 else float(fwd_pkts)
    byte_ratio = fwd_bytes / bwd_bytes if bwd_bytes > 0 else float(fwd_bytes)

    features = {
        'src_ip': src_ip,
        'src_port': int(src_port),
        'dst_ip': dst_ip,
        'dst_port': int(dst_port),
        'protocol': int(protocol),
        'start_time': flow_data['start_time'],
        'end_time': flow_data['last_seen'],
        'duration': duration,

        'fwd_pkts': fwd_pkts,
        'bwd_pkts': bwd_pkts,
        'fwd_bytes': fwd_bytes,
        'bwd_bytes': bwd_bytes,
        'tot_pkts': total_pkts,
        'tot_bytes': total_bytes,

        'fwd_iat_mean': np.mean(fwd_iats) if fwd_iats else 0.0,
        'bwd_iat_mean': np.mean(bwd_iats) if bwd_iats else 0.0,
        'fwd_iat_max': np.max(fwd_iats) if fwd_iats else 0.0,
        'bwd_iat_max': np.max(bwd_iats) if bwd_iats else 0.0,

        'fwd_syn': flow_data['fwd_syn'],
        'fwd_fin': flow_data['fwd_fin'],
        'bwd_syn': flow_data['bwd_syn'],
        'bwd_fin': flow_data['bwd_fin'],

        # --- Computed Averages & Rates ---
        'avg_fwd_pkt_size': np.mean(fwd_lengths) if fwd_lengths else 0.0,
        'avg_bwd_pkt_size': np.mean(bwd_lengths) if bwd_lengths else 0.0,
        'avg_pkt_size': np.mean(all_lengths) if all_lengths else 0.0,
        'avg_pkts_per_sec': total_pkts / duration,
        'avg_bytes_per_sec': total_bytes / duration,
        'flow_byts_s': total_bytes / duration,

        # --- Engineered Symmetry Features ---
        'pkt_ratio': pkt_ratio,
        'byte_ratio': byte_ratio
    }
    return features

def process_pcap_in_chunks(pcap_path, output_csv, progress_tracker):
    """
    Reads a PCAP file iteratively, cutting active connections into 15-second windows.
    """
    print(f"{progress_tracker} Processing: {os.path.basename(pcap_path)}")
    active_flows = {}
    completed_chunks = []
    packet_count = 0

    try:
        with PcapReader(pcap_path) as pcap_reader:
            for pkt in pcap_reader:
                packet_count += 1
                if packet_count % 100000 == 0:
                    print(f"    ... scanned {packet_count:,} packets. Active flows in memory: {len(active_flows)}")

                if not pkt.haslayer(IP): continue

                ip_layer = pkt[IP]
                syn_flag, fin_flag = 0, 0

                if pkt.haslayer(TCP):
                    src_port, dst_port, proto = pkt[TCP].sport, pkt[TCP].dport, 6
                    tcp_flags = pkt[TCP].flags
                    if 'S' in tcp_flags: syn_flag = 1
                    if 'F' in tcp_flags: fin_flag = 1
                elif pkt.haslayer(UDP):
                    src_port, dst_port, proto = pkt[UDP].sport, pkt[UDP].dport, 17
                else:
                    continue

                src_ip, dst_ip = ip_layer.src, ip_layer.dst

                if src_ip < dst_ip:
                    flow_id = (src_ip, dst_ip, str(src_port), str(dst_port), str(proto))
                    direction = 'fwd'
                else:
                    flow_id = (dst_ip, src_ip, str(dst_port), str(src_port), str(proto))
                    direction = 'bwd'

                timestamp = float(pkt.time)
                pkt_len = len(pkt)

                if flow_id not in active_flows:
                    active_flows[flow_id] = {
                        'start_time': timestamp, 'last_seen': timestamp,
                        'fwd_pkt_lengths': [], 'bwd_pkt_lengths': [],
                        'fwd_iats': [], 'bwd_iats': [],
                        'fwd_syn': 0, 'fwd_fin': 0, 'bwd_syn': 0, 'bwd_fin': 0
                    }

                flow = active_flows[flow_id]

                if timestamp - flow['start_time'] >= CHUNK_WINDOW_SEC:
                    completed_chunks.append(extract_flow_features(flow_id, flow))
                    active_flows[flow_id] = {
                        'start_time': timestamp, 'last_seen': timestamp,
                        'fwd_pkt_lengths': [], 'bwd_pkt_lengths': [],
                        'fwd_iats': [], 'bwd_iats': [],
                        'fwd_syn': 0, 'fwd_fin': 0, 'bwd_syn': 0, 'bwd_fin': 0
                    }
                    flow = active_flows[flow_id]

                iat = timestamp - flow['last_seen']
                if direction == 'fwd':
                    flow['fwd_pkt_lengths'].append(pkt_len)
                    if len(flow['fwd_pkt_lengths']) > 1: flow['fwd_iats'].append(iat)
                    flow['fwd_syn'] += syn_flag
                    flow['fwd_fin'] += fin_flag
                else:
                    flow['bwd_pkt_lengths'].append(pkt_len)
                    if len(flow['bwd_pkt_lengths']) > 1: flow['bwd_iats'].append(iat)
                    flow['bwd_syn'] += syn_flag
                    flow['bwd_fin'] += fin_flag

                flow['last_seen'] = timestamp

                if packet_count % 10000 == 0:
                    dead_flows = [fid for fid, f in active_flows.items() if (timestamp - f['last_seen']) > IDLE_TIMEOUT_SEC]
                    for fid in dead_flows:
                        if len(active_flows[fid]['fwd_pkt_lengths']) + len(active_flows[fid]['bwd_pkt_lengths']) > 2:
                            completed_chunks.append(extract_flow_features(fid, active_flows[fid]))
                        del active_flows[fid]

        for fid, f in active_flows.items():
            if len(f['fwd_pkt_lengths']) + len(f['bwd_pkt_lengths']) > 2:
                completed_chunks.append(extract_flow_features(fid, f))

        if completed_chunks:
            df = pd.DataFrame(completed_chunks)
            df.to_csv(output_csv, index=False)
            print(f"    [+] Saved {len(df)} time-windows to {os.path.basename(output_csv)}\n")
        else:
            print("    [-] No valid traffic data found.\n")

    except Exception as e:
        print(f"    [!] Error processing {os.path.basename(pcap_path)}: {e}\n")


# --- 3. EXECUTE OVER DATASET (WITH PRE-SCAN AND FILTERING) ---
start_timer = time.time()

# Step A: Pre-Scan and Filter
all_target_files = []
skipped_files = []

for folder in PCAP_FOLDERS:
    if os.path.exists(folder):
        for file in os.listdir(folder):
            if file.endswith((".pcap", ".pcapng")):
                # Check against exclusion list (case-insensitive)
                file_lower = file.lower()
                if any(keyword in file_lower for keyword in EXCLUDE_KEYWORDS):
                    skipped_files.append(file)
                    continue

                all_target_files.append((folder, file))

total_files = len(all_target_files)

print(f"\n{'='*60}")
print(f"[*] Pre-Scan Complete: Found {total_files} valid files to process.")
if skipped_files:
    print(f"[*] Ignored {len(skipped_files)} remote-control/SSH files (e.g., {skipped_files[0]}).")
print(f"{'='*60}\n")

# Step B: Process files with progress tracking
for idx, (folder, pcap_file) in enumerate(all_target_files, 1):

    full_pcap_path = os.path.join(folder, pcap_file)
    base_name = os.path.splitext(pcap_file)[0]
    csv_filename = base_name + ".csv"
    full_csv_path = os.path.join(CSV_OUTPUT_DIR, csv_filename)

    percent_done = (idx / total_files) * 100
    progress_str = f"[{idx}/{total_files}] ({percent_done:.1f}%)"

    process_pcap_in_chunks(full_pcap_path, full_csv_path, progress_str)

print(f"\n{'='*60}")
print(f"[*] Feature Extraction 100% Complete!")
print(f"[*] Total Processing time: {(time.time() - start_timer)/60:.2f} minutes.")
print(f"{'='*60}")

"""now after we converted all the files we need to classify them,
first we need to list all the file names to see what we converted.

the code ↓
"""

import os

# The path to your output CSV folder
csv_folder_path = "/content/drive/MyDrive/Colab_Notebooks/pcaps/converted_CSVs"

print(f"Scanning folder: {csv_folder_path}\n" + "="*50)

if os.path.exists(csv_folder_path):
    # Get all CSV files and sort them alphabetically
    all_csv_files = sorted([f for f in os.listdir(csv_folder_path) if f.endswith('.csv')])

    if len(all_csv_files) == 0:
        print("The folder exists, but no CSV files were found inside it.")
    else:
        for idx, filename in enumerate(all_csv_files, 1):
            print(f"{idx}. {filename}")

        print("="*50)
        print(f"Total CSV files found: {len(all_csv_files)}")
else:
    print(f"Error: The folder was not found. Please double-check the path.")

"""To train an accurate Machine Learning model, we must group our raw traffic into logical classes. We are classifying the dataset into **4 categories**.

The categorization is not based on what the app *looks* like to a human, but rather how the mathematical shape of the data packets behaves on the network.

### 1. Streaming (Netflix, YouTube, Vimeo, Spotify)
* **Network Behavior:** Streaming platforms do not download data continuously. They download a large chunk of video/audio into a buffer, pause while the user consumes it, and then download another chunk.
* **Mathematical Signature:** High volume bursts of maximum-size packets, followed by distinct periods of zero traffic (pauses).

### 2. File Transfer (SCP, SFTP, Rsync, Skype File Transfer)
* **Network Behavior:** File transfers attempt to move a large block of data from Point A to Point B as fast as the network allows.
* **Mathematical Signature:** Extremely high `avg_bytes_per_sec`, highly asymmetrical (mostly downloading or mostly uploading), with **no intentional pauses**.

### 3. Real-Time Call (VoIP, Skype/Hangouts/Facebook Audio & Video)
* **Network Behavior:** Live two-way communication requires extremely low latency.
* **Mathematical Signature:** A steady, continuous, symmetrical stream of medium-sized packets. There are no massive spikes, but also no periods of total silence, creating a flat "heartbeat" of data.

### 4. Messaging & Async Comm (Email, Skype Chat, WhatsApp, IMAP/SMTP)
* **Network Behavior:** Both modern chat and email apps rely on persistent, dormant connections (like WebSockets or IMAP IDLE). They stay connected to a server to receive instant push notifications.
* **Mathematical Signature:** Very low baseline bandwidth consisting of regular, tiny "keep-alive" packets. This is occasionally interrupted by sudden, brief bursts of bandwidth when an actual text message, photo, or email attachment is sent or received.

***
**Note on True Infrastructure:** The AI is trained specifically on these human-driven applications. Low-level machine background noise (like DNS on Port 53 or NTP on Port 123) is handled separately in our live application using Hardcoded Heuristic Overrides, where it is classified strictly as "Infrastructure".
"""

# ==============================================================================
# Data Consolidation and 4-Class Labeling
# ==============================================================================
import os
import pandas as pd
import glob

# --- 1. CONFIGURATION ---
CSV_INPUT_DIR = "/content/drive/MyDrive/Colab_Notebooks/pcaps/converted_CSVs"
MASTER_OUTPUT_FILE = "/content/drive/MyDrive/Colab_Notebooks/mit_unb_combined.csv"

print(f"[*] Scanning for chunked CSVs in: {CSV_INPUT_DIR}")
all_csv_files = glob.glob(os.path.join(CSV_INPUT_DIR, "*.csv"))

if not all_csv_files:
    print("[-] No CSV files found. Please check the directory path.")
else:
    print(f"[+] Found {len(all_csv_files)} CSV files. Beginning consolidation...")

train_dfs = []

# --- 2. ADVANCED LABELING LOGIC (4-CLASS SYSTEM) ---
for file in all_csv_files:
    try:
        temp_df = pd.read_csv(file)
        filename_lower = os.path.basename(file).lower()

        # 1. File Transfer
        if "ftp" in filename_lower or "scp" in filename_lower or "rsync" in filename_lower or "skype_file" in filename_lower:
            temp_df['traffic_type'] = 'File_Transfer'

        # 2. Streaming
        elif "netflix" in filename_lower or "youtube" in filename_lower or "vimeo" in filename_lower or "spotify" in filename_lower:
            temp_df['traffic_type'] = 'Streaming'

        # 3. Real-Time Call
        elif "audio" in filename_lower or "video" in filename_lower or "voip" in filename_lower:
            temp_df['traffic_type'] = 'RealTime_Call'

        # 4. Messaging & Async Comm (Merged Chat and Mail)
        elif any(keyword in filename_lower for keyword in ["chat", "skype", "hangout", "aim", "icq", "email", "imap", "pop3", "smtp"]):
            temp_df['traffic_type'] = 'Messaging'

        # Fallback (Ignore unknown files, including SSH and RDP, to keep the training data pure)
        else:
            print(f"[?] Unknown traffic type, skipping: {os.path.basename(file)}")
            continue

        train_dfs.append(temp_df)

    except Exception as e:
        print(f"[!] Error reading {file}: {e}")

# --- 3. MERGE, SHUFFLE, AND SAVE ---
if train_dfs:
    # Concatenate all the individual DataFrames into one massive table
    master_train_df = pd.concat(train_dfs, ignore_index=True)

    # SHUFFLE THE DATA: Crucial for Neural Networks!
    master_train_df = master_train_df.sample(frac=1, random_state=42).reset_index(drop=True)

    # Save the final consolidated file
    master_train_df.to_csv(MASTER_OUTPUT_FILE, index=False)

    print("\n" + "="*50)
    print(f"SUCCESS: Master training dataset created!")
    print(f"Total Time-Windows (Rows): {master_train_df.shape[0]}")
    print(f"Total Features (Columns): {master_train_df.shape[1]}")
    print(f"Saved to: {MASTER_OUTPUT_FILE}")
    print("="*50)

    # Display the final class distribution to ensure the logic worked
    print("\nFinal Class Distribution:")
    print(master_train_df['traffic_type'].value_counts())

"""##Why Split the Data?
We split the data to ensure our model actually learns patterns instead of just memorizing examples. The Training Set (64%) is where the model learns. The Validation Set (16%) acts as a practice quiz to tune settings and prevent overfitting. Finally, the Test Set (20%) serves as the final exam on completely unseen data to evaluate its true, real-world performance.

spliting code ↓
"""

import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Load your combined dataset
print("Loading dataset...")
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/mit_unb_combined.csv')

# 2. Perform the 80/20 split
# test_size=0.20 means 20% goes to the test set, and 80% stays in the train set.
# stratify=df['traffic_type'] ensures the ratio of traffic types stays the same in both sets.
print("Splitting data into 80% Train and 20% Test...")
train_df, test_df = train_test_split(df, test_size=0.20, stratify=df['traffic_type'], random_state=42)

# 3. Save the new datasets to CSV files
print("Saving split datasets to CSV...")
train_df.to_csv('/content/drive/MyDrive/Colab_Notebooks/train_data_80.csv', index=False)

test_df.to_csv('/content/drive/MyDrive/Colab_Notebooks/test_data_20.csv', index=False)

# 4. Print the results to verify
total_rows = len(df)
print("\n--- Split Results ---")
print(f"Original dataset: {total_rows} rows")
print(f"Train set (80%):  {len(train_df)} rows ({len(train_df)/total_rows*100:.1f}%)")
print(f"Test set (20%):   {len(test_df)} rows ({len(test_df)/total_rows*100:.1f}%)")
print("Done! Files 'train_data_80.csv' and 'test_data_20.csv' have been created.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load your 80% train set
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/train_data_80.csv')

# Configure a beautiful, clean aesthetic for the notebook
sns.set_theme(style="whitegrid", font_scale=1.2)

# ==========================================
# 1. Traffic Asymmetry (Scatter Plot)
# ==========================================
plt.figure(figsize=(14, 8))
df_sorted = df.sort_values('traffic_type') # Sort so small classes aren't hidden
sns.scatterplot(data=df_sorted, x='fwd_bytes', y='bwd_bytes', hue='traffic_type',
                alpha=0.6, palette='bright', s=50, edgecolor=None)
plt.xscale('log')
plt.yscale('log')

# Add 1:1 symmetry line
plt.plot([1, df['fwd_bytes'].max()], [1, df['fwd_bytes'].max()],
         color='black', linestyle='--', linewidth=1.5, alpha=0.8, label='1:1 Symmetry Line')

plt.title('Traffic Asymmetry: Forward (Upload) vs Backward (Download) Bytes', fontsize=18, pad=15)
plt.xlabel('Forward Bytes (Log Scale)', fontsize=14)
plt.ylabel('Backward Bytes (Log Scale)', fontsize=14)
plt.legend(title='Traffic Type', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ==========================================
# 2. bytes Intensity (Violin Plot)
# ==========================================
plt.figure(figsize=(14, 8))
df['log_bytes_per_sec'] = np.log1p(df['avg_bytes_per_sec'])
sns.violinplot(data=df, x='traffic_type', y='log_bytes_per_sec', palette='Set2', inner='quartile')
plt.title('bytes Intensity: Log(Bytes per Second)', fontsize=18, pad=15)
plt.xlabel('Traffic Type', fontsize=14)
plt.ylabel('Log(Bytes per Second)', fontsize=14)
plt.tight_layout()
plt.show()

# ==========================================
# 3. Packet Intensity (Boxen Plot)
# ==========================================
plt.figure(figsize=(14, 8))
df['log_pkts_per_sec'] = np.log1p(df['avg_pkts_per_sec'])
sns.boxenplot(data=df, x='traffic_type', y='log_pkts_per_sec', palette='plasma')
plt.title('Packet Intensity: Packets per Second by Traffic Type', fontsize=18, pad=15)
plt.xlabel('Traffic Type', fontsize=14)
plt.ylabel('Log(Packets per Second)', fontsize=14)
plt.tight_layout()
plt.show()

# ==========================================
# 4. Behavioral Fingerprint (TCP Flag Heatmap)
# ==========================================
flag_cols = ['fwd_syn', 'fwd_fin', 'bwd_syn', 'bwd_fin']
flag_means = df.groupby('traffic_type')[flag_cols].mean()

plt.figure(figsize=(12, 7))
sns.heatmap(flag_means, annot=True, cmap='YlOrRd', fmt=".4f", annot_kws={"size": 13})
plt.title('Behavioral Fingerprint: Average TCP Flags per Session', fontsize=18, pad=15)
plt.xlabel('TCP Flag Type', fontsize=14)
plt.ylabel('Traffic Type', fontsize=14)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Define the file paths for your Drive
file1_path = '/content/drive/MyDrive/Colab_Notebooks/pcaps/converted_CSVs/facebook_video1a.csv'
file2_path = '/content/drive/MyDrive/Colab_Notebooks/pcaps/converted_CSVs/nonvpn_youtube_capture3.csv'

# 2. Load datasets and tag them
df_fb = pd.read_csv(file1_path)
df_fb['Source'] = 'Facebook Video'

df_yt = pd.read_csv(file2_path)
df_yt['Source'] = 'YouTube'

# Combine into one DataFrame for easy side-by-side plotting
df = pd.concat([df_fb, df_yt], ignore_index=True)

# 3. Get only numeric columns for histogram plotting
# (Dropping ports and timestamps as they don't make good histograms)
numeric_cols = df.select_dtypes(include=np.number).columns
cols_to_drop = ['src_port', 'dst_port', 'start_time', 'end_time']
numeric_cols = [col for col in numeric_cols if col not in cols_to_drop]

# 4. Determine the number of rows and columns for the subplot grid
num_features = len(numeric_cols)

if num_features == 0:
    print("No numeric columns to plot histograms for.")
else:
    n_cols = 3  # 3 columns wide, just like your example
    n_rows = (num_features + n_cols - 1) // n_cols

    # Make the figure size dynamically scale based on rows
    plt.figure(figsize=(n_cols * 6, n_rows * 4))
    sns.set_theme(style="whitegrid")

    for i, col in enumerate(numeric_cols):
        plt.subplot(n_rows, n_cols, i + 1)

        # Plot both Facebook and YouTube on the same axis using 'hue'
        # Added common_norm=False so both distributions scale to their own heights cleanly
        sns.histplot(data=df, x=col, hue='Source', kde=True,
                     palette=['#1877F2', '#FF0000'], alpha=0.5,
                     element="step", common_norm=False, bins=30)

        plt.title(f'Distribution of {col}', fontsize=14)
        plt.xlabel(col, fontsize=12)
        plt.ylabel('Frequency', fontsize=12)

    plt.tight_layout()
    plt.show()