# -*- coding: utf-8 -*-
"""final_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhxWY08tG4s_m62Ofzc0eeVt-1hUiMio

# Final Evaluation: Testing the Winning Model

The raw data was downloaded from the sites of: [MIT](https://www.ll.mit.edu/r-d/datasets/vpnnonvpn-network-application-traffic-dataset-vnat), a premier engineering university, and the [University of New Brunswick (UNB)](https://www.unb.ca//cic/datasets/vpn.html), a leading cybersecurity research hub.

In this final notebook, we put our winning Random Forest model to the ultimate test. We will load the model and the label encoder we saved previously, and run them against our completely unseen `test_data_20.csv`.

Because this data was kept strictly separated during the training and validation phases, the resulting accuracy will represent the true, real-world performance of our machine learning pipeline.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from google.colab import drive

# Mount Google Drive to access the saved files
print("Mounting Google Drive...")
drive.mount('/content/drive')

# 1. Define your exact file paths
model_path = '/content/drive/MyDrive/Colab_Notebooks/rf_model.pkl'
encoder_path = '/content/drive/MyDrive/Colab_Notebooks/label_encoder.pkl'
test_data_path = '/content/drive/MyDrive/Colab_Notebooks/test_data_20.csv'

# 2. Load the Model and the Encoder
print("\nLoading the winning Random Forest model and Label Encoder...")
rf_model = joblib.load(model_path)
encoder = joblib.load(encoder_path)

# 3. Load the completely unseen 20% Test Data
print("Loading the unseen test data...")
df_test = pd.read_csv(test_data_path)

print(f"Test data loaded successfully. Shape: {df_test.shape}")

# Separate Features (X) and Target (y) for the test dataset
# We must drop the exact same columns we dropped during training!
X_test = df_test.drop(columns=['traffic_type', 'src_ip', 'dst_ip','src_port','dst_port', 'start_time', 'end_time'])
y_test_text = df_test['traffic_type']

# Convert the text labels into the exact same numbers the model was trained on
y_test_encoded = encoder.transform(y_test_text)

print(f"Features ready for prediction. Shape: {X_test.shape}")

# Make the predictions on the unseen data
print("Running final predictions...")
y_test_pred = rf_model.predict(X_test)

# Calculate Final Accuracy
final_accuracy = accuracy_score(y_test_encoded, y_test_pred)
print(f"\n=========================================")
print(f"  ULTIMATE TEST ACCURACY: {final_accuracy:.4f} ({(final_accuracy*100):.2f}%)")
print(f"=========================================\n")

# Generate a detailed Classification Report
target_names = encoder.classes_
print("Detailed Classification Report:")
print(classification_report(y_test_encoded, y_test_pred, target_names=target_names))

# Generate the Confusion Matrix and normalize it by the actual truth (rows)
cm_percentage = confusion_matrix(y_test_encoded, y_test_pred, normalize='true')

# Plot it as a beautiful Heatmap
plt.figure(figsize=(10, 8))
sns.set_theme(style="white")

sns.heatmap(cm_percentage, annot=True, fmt='.0%', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names,
            cbar=False, annot_kws={"size": 12})

plt.title('Final Confusion Matrix (Percentages): Predictions vs. Reality', fontsize=18, pad=20)
plt.xlabel('What the Model Predicted', fontsize=14, labelpad=10)
plt.ylabel('The Actual Traffic Type', fontsize=14, labelpad=10)
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.yticks(rotation=0, fontsize=11)
plt.tight_layout()
plt.show()

"""### Project Conclusion
Our machine learning pipeline was a complete success. By properly splitting our data, scaling where necessary, and evaluating multiple architectures (including Deep Neural Networks and 1D CNNs), we determined that a tuned **Random Forest** was the most effective algorithm for this tabular dataset.

When subjected to the ultimate test against completely unseen data, the model achieved a remarkable final accuracy. Furthermore, by analyzing the **Confusion Matrix** above, we can see exactly where the model excels and where network traffic classes might logically overlap in behavior. This concludes the model building and evaluation phase!
"""