# -*- coding: utf-8 -*-
"""nn_models_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iY1q1_PVUmYbGri1Y1D7419Cy028NHR

# Neural Network Architectures: DNN vs. 1D CNN

The raw data was downloaded from the sites of: [MIT](https://www.ll.mit.edu/r-d/datasets/vpnnonvpn-network-application-traffic-dataset-vnat), a premier engineering university, and the [University of New Brunswick (UNB)](https://www.unb.ca//cic/datasets/vpn.html), a leading cybersecurity research hub.

In this notebook, we are going to test two fundamentally different Neural Network architectures to see which mathematical approach best classifies network traffic.
We will compare a fully connected Deep Neural Network (DNN) against a 1D Convolutional Neural Network (1D CNN), which acts as a spatial feature-extractor.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical

# 1. Load and prepare the data
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/train_data_80.csv')
X = df.drop(columns=['traffic_type', 'src_ip', 'src_port','dst_port','dst_ip', 'start_time', 'end_time'])
y = df['traffic_type']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, stratify=y, random_state=42)

# 2. Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

# 3. Encode labels
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_val_encoded = encoder.transform(y_val)
num_classes = len(encoder.classes_)
y_train_dummy = to_categorical(y_train_encoded, num_classes=num_classes)
y_val_dummy = to_categorical(y_val_encoded, num_classes=num_classes)

"""### Architecture 1: Deep Feedforward Network (DNN)
This model connects every feature to every neuron. It is highly optimized with Batch Normalization (to stabilize learning) and Dropout (to prevent overfitting). It learns by looking at the global state of all features simultaneously.
"""

model_dnn = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model_dnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

print("Training DNN Architecture...")
history_dnn = model_dnn.fit(
    X_train_scaled, y_train_dummy,
    validation_data=(X_val_scaled, y_val_dummy),
    epochs=50, batch_size=64, callbacks=[early_stop], verbose=1
)

"""### Architecture 2: 1D Convolutional Neural Network
Instead of looking at everything globally, this model uses a moving filter (Conv1D) to scan across the feature array, extracting local patterns. We then use MaxPooling to compress those patterns, flatten them out, and make a final prediction.

*Note: CNNs require 3-dimensional input, so we must reshape our 2D tabular data from `(samples, features)` into `(samples, features, 1)`.*
"""

# Reshape data for the CNN (Adding the 3rd dimension: "channels")
X_train_cnn = X_train_scaled.reshape(X_train_scaled.shape[0], X_train_scaled.shape[1], 1)
X_val_cnn = X_val_scaled.reshape(X_val_scaled.shape[0], X_val_scaled.shape[1], 1)

model_cnn = Sequential([
    # The "flashlight" filter scanning the features
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X_train_cnn.shape[1], 1)),
    BatchNormalization(),
    MaxPooling1D(pool_size=2), # Shrinks the data to keep only the strongest signals

    Conv1D(filters=128, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Flatten(), # Flattens the 3D data back to 1D for the final decision

    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("\nTraining 1D CNN Architecture...")
history_cnn = model_cnn.fit(
    X_train_cnn, y_train_dummy,
    validation_data=(X_val_cnn, y_val_dummy),
    epochs=50, batch_size=64, callbacks=[early_stop], verbose=1
)

# --- Final Comparison ---
print("\n=== Architecture Showdown Results ===")
print(f"Standard DNN Best Validation Accuracy:  {max(history_dnn.history['val_accuracy']):.4f}")
print(f"1D CNN Best Validation Accuracy:        {max(history_cnn.history['val_accuracy']):.4f}")

import matplotlib.pyplot as plt

# Function to plot learning curves
def plot_history(history, model_name):
    plt.figure(figsize=(12, 4))

    # Plot Accuracy
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', color='blue')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='orange')
    plt.title(f'{model_name} - Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    # Plot Loss
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', color='blue')
    plt.plot(history.history['val_loss'], label='Validation Loss', color='orange')
    plt.title(f'{model_name} - Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

# Plot the graphs for both models
plot_history(history_dnn, "Standard DNN")
plot_history(history_cnn, "1D CNN")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# 1. יצירת תחזיות לשני המודלים (DNN ו-CNN) על סט הולידציה
y_pred_dnn_prob = model_dnn.predict(X_val_scaled)
y_pred_dnn = np.argmax(y_pred_dnn_prob, axis=1)

y_pred_cnn_prob = model_cnn.predict(X_val_cnn)
y_pred_cnn = np.argmax(y_pred_cnn_prob, axis=1)

# 2. חילוץ התוויות האמיתיות (Ground Truth) מתוך משתני הולידציה
y_true = np.argmax(y_val_dummy, axis=1)

# 3. חילוץ שמות המחלקות ישירות מה-Encoder שהוגדר למעלה
target_names = encoder.classes_

# 4. חישוב מטריצות הערבוב (באחוזים לכל שורה)
cm_dnn = confusion_matrix(y_true, y_pred_dnn, normalize='true')
cm_cnn = confusion_matrix(y_true, y_pred_cnn, normalize='true')

# 5. הגדרת התצוגה (גרף לצד גרף בגודל מתאים)
fig, axes = plt.subplots(1, 2, figsize=(20, 8))
sns.set_theme(style="white")

# ציור מטריצת הערבוב של ה-DNN (בגווני סגול)
sns.heatmap(cm_dnn, annot=True, fmt='.1%', cmap='Purples',
            xticklabels=target_names, yticklabels=target_names,
            cbar=False, annot_kws={"size": 14}, ax=axes[0])
axes[0].set_title('Standard DNN Confusion Matrix', fontsize=20, pad=20)
axes[0].set_xlabel('Predicted Label', fontsize=16, labelpad=10)
axes[0].set_ylabel('True Label', fontsize=16, labelpad=10)
axes[0].tick_params(axis='x', rotation=45, labelsize=14)
axes[0].tick_params(axis='y', rotation=0, labelsize=14)

# ציור מטריצת הערבוב של ה-1D CNN (בגווני כחול)
sns.heatmap(cm_cnn, annot=True, fmt='.1%', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names,
            cbar=False, annot_kws={"size": 14}, ax=axes[1])
axes[1].set_title('1D CNN Confusion Matrix', fontsize=20, pad=20)
axes[1].set_xlabel('Predicted Label', fontsize=16, labelpad=10)
axes[1].set_ylabel('True Label', fontsize=16, labelpad=10)
axes[1].tick_params(axis='x', rotation=45, labelsize=14)
axes[1].tick_params(axis='y', rotation=0, labelsize=14)

plt.tight_layout()
plt.show()

"""### Conclusion
By comparing the learning curves and final metrics, the **Standard Deep Neural Network (DNN)** outperformed the **1D CNN**, achieving a peak validation accuracy of **86.62%** compared to the CNN's **82.77%**.

This outcome makes perfect logical sense for our dataset. Because our network traffic data is tabular (a collection of distinct, independent statistics like bytes, packet sizes, and durations), the DNN's global approach—where it looks at all features simultaneously—proved much more effective than the CNN's sliding spatial filter.

The DNN is our official Neural Network winner! We will save this model and put it to the ultimate test against our completely unseen 20% Test Set in the final notebook.
"""