import customtkinter as ctk
from tkinter import ttk, messagebox, filedialog
import pandas as pd
import time
import sys
import os
import warnings
import matplotlib

matplotlib.use("TkAgg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from fpdf import FPDF

# Mute warnings
warnings.filterwarnings("ignore")

from sniffer import PacketSniffer
from analyzer import TrafficAnalyzer

# --- THEME ---
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("dark-blue")

# --- COLORS ---
COLOR_BG = "#0f0f0f"
COLOR_PANEL = "#1a1a1a"
COLOR_ACCENT = "#3B8ED0"
COLOR_TEXT_MAIN = "white"
COLOR_TEXT_DIM = "#a0a0a0"


class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'NetWatch Pro // Security Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by NetWatch Pro - Page ' + str(self.page_no()), 0, 0, 'C')


class ModernNetWatchGUI(ctk.CTk):
    def __init__(self, queue):
        super().__init__()

        self.title("NetWatch Pro // Command Center")
        self.geometry("1600x950")
        self.protocol("WM_DELETE_WINDOW", self.on_close)

        self.queue = queue
        self.running = True
        self.filter_text = ""

        self.analyzer = TrafficAnalyzer()
        self.sniffer = PacketSniffer(self.queue)

        self.setup_ui()
        self.update_loop()

    def setup_ui(self):
        self.grid_columnconfigure(0, weight=0)
        self.grid_columnconfigure(1, weight=3)
        self.grid_columnconfigure(2, weight=0)
        self.grid_rowconfigure(0, weight=1)

        # 1. SIDEBAR
        self.sidebar = ctk.CTkFrame(self, width=250, corner_radius=0, fg_color=COLOR_PANEL)
        self.sidebar.grid(row=0, column=0, sticky="nsew")
        self.sidebar.grid_propagate(False);
        self.sidebar.pack_propagate(False)
        self.setup_sidebar_content()

        # 2. MAIN AREA
        self.main_frame = ctk.CTkFrame(self, corner_radius=0, fg_color=COLOR_BG)
        self.main_frame.grid(row=0, column=1, sticky="nsew")
        self.main_frame.grid_rowconfigure(0, weight=0)
        self.main_frame.grid_rowconfigure(1, weight=1)
        self.main_frame.grid_rowconfigure(2, weight=0)
        self.main_frame.grid_rowconfigure(3, weight=2)
        self.main_frame.grid_columnconfigure(0, weight=1)

        self.stats_frame = ctk.CTkFrame(self.main_frame, fg_color="transparent")
        self.stats_frame.grid(row=0, column=0, sticky="ew", padx=20, pady=(20, 10))
        self.setup_stats_bar()

        self.graph_frame = ctk.CTkFrame(self.main_frame, fg_color=COLOR_PANEL, corner_radius=10)
        self.graph_frame.grid(row=1, column=0, sticky="nsew", padx=20, pady=10)
        self.setup_graphs()

        self.search_frame = ctk.CTkFrame(self.main_frame, fg_color="transparent")
        self.search_frame.grid(row=2, column=0, sticky="ew", padx=20, pady=(5, 5))
        self.setup_search_bar()

        self.list_frame = ctk.CTkFrame(self.main_frame, fg_color=COLOR_PANEL, corner_radius=10)
        self.list_frame.grid(row=3, column=0, sticky="nsew", padx=20, pady=(0, 20))
        self.setup_table()

        # 3. INSPECTOR PANEL
        self.inspector_frame = ctk.CTkFrame(self, width=320, corner_radius=0, fg_color=COLOR_PANEL)
        self.inspector_frame.grid(row=0, column=2, sticky="nsew")
        self.inspector_frame.grid_propagate(False);
        self.inspector_frame.pack_propagate(False)
        self.setup_inspector()

    def setup_sidebar_content(self):
        ctk.CTkLabel(self.sidebar, text="NetWatch", font=("Roboto Medium", 32, "bold"), text_color=COLOR_ACCENT).pack(
            pady=(40, 0))
        ctk.CTkLabel(self.sidebar, text="COMMAND CENTER", font=("Roboto", 12, "bold"), text_color=COLOR_TEXT_DIM).pack(
            pady=(0, 30))

        self.btn_start = ctk.CTkButton(self.sidebar, text="▶ START MONITORING", height=45, fg_color="#27ae60",
                                       hover_color="#2ecc71", font=("Roboto", 12, "bold"), command=self.start_system)
        self.btn_start.pack(padx=20, pady=10, fill="x")

        self.btn_stop = ctk.CTkButton(self.sidebar, text="■ STOP SYSTEM", height=45, fg_color="#c0392b",
                                      hover_color="#e74c3c", font=("Roboto", 12, "bold"), state="disabled",
                                      command=self.stop_system)
        self.btn_stop.pack(padx=20, pady=10, fill="x")

        ctk.CTkButton(self.sidebar, text="⬇ EXPORT REPORT", height=35, fg_color="#2c3e50", font=("Roboto", 12),
                      command=self.export_data).pack(padx=20, pady=(40, 10), fill="x")

        self.lbl_status = ctk.CTkLabel(self.sidebar, text="● SYSTEM READY", font=("Roboto Mono", 10), text_color="gray")
        self.lbl_status.pack(side="bottom", pady=20)

    def setup_search_bar(self):
        lbl_search = ctk.CTkLabel(self.search_frame, text="FILTER TRAFFIC:", font=("Roboto", 12, "bold"),
                                  text_color=COLOR_TEXT_DIM)
        lbl_search.pack(side="left", padx=(0, 10))
        self.entry_search = ctk.CTkEntry(self.search_frame,
                                         placeholder_text="Type protocol (UDP), IP (192.168...), or Port...", width=300)
        self.entry_search.pack(side="left", fill="x", expand=True)
        self.entry_search.bind("<KeyRelease>", self.update_filter)

    def update_filter(self, event):
        self.filter_text = self.entry_search.get().lower()

    def setup_inspector(self):
        # Header
        ctk.CTkLabel(self.inspector_frame, text="PACKET INSPECTOR", font=("Roboto", 18, "bold"),
                     text_color="white").pack(pady=(30, 15))

        # --- SOURCE SECTION ---
        # IP Address (Bigger: 16 -> 19)
        self.insp_src = ctk.CTkLabel(self.inspector_frame, text="---", font=("Roboto Mono", 19, "bold"),
                                     text_color=COLOR_ACCENT)
        self.insp_src.pack(pady=(5, 0))

        # Country (Bigger: 10 -> 14)
        self.insp_src_country = ctk.CTkLabel(self.inspector_frame, text="Checking...", font=("Roboto", 14),
                                             text_color=COLOR_TEXT_DIM)
        self.insp_src_country.pack()

        # Arrow
        ctk.CTkLabel(self.inspector_frame, text="↓", font=("Arial", 24, "bold"), text_color=COLOR_TEXT_DIM).pack(
            pady=5)

        # --- DESTINATION SECTION ---
        # IP Address (Bigger: 16 -> 19)
        self.insp_dst = ctk.CTkLabel(self.inspector_frame, text="---", font=("Roboto Mono", 19, "bold"),
                                     text_color="#e74c3c")
        self.insp_dst.pack(pady=(0, 0))

        # Country (Bigger: 10 -> 14)
        self.insp_dst_country = ctk.CTkLabel(self.inspector_frame, text="Checking...", font=("Roboto", 14),
                                             text_color=COLOR_TEXT_DIM)
        self.insp_dst_country.pack()

        # --- DETAILS CONTAINER ---
        self.detail_container = ctk.CTkFrame(self.inspector_frame, fg_color=COLOR_BG, corner_radius=8)
        self.detail_container.pack(fill="x", padx=15, pady=20)

        self.insp_proto = self.create_detail_row("PROTOCOL", "---")
        self.insp_port = self.create_detail_row("PORT", "---")
        self.insp_len = self.create_detail_row("SIZE", "---")
        self.insp_time = self.create_detail_row("TIME", "---")

        # --- INSIGHTS ---
        ctk.CTkLabel(self.inspector_frame, text="PACKET INSIGHTS", font=("Roboto", 14, "bold"), text_color="white",
                     anchor="w").pack(fill="x", padx=20, pady=(15, 5))

        # Status Text (Bigger: 11 -> 13)
        self.insp_status = ctk.CTkLabel(self.inspector_frame, text="Select a packet...", font=("Roboto", 13),
                                        text_color=COLOR_TEXT_DIM, justify="left", wraplength=280)
        self.insp_status.pack(fill="x", padx=20)

    def create_detail_row(self, label, value):
        row = ctk.CTkFrame(self.detail_container, fg_color="transparent")
        row.pack(fill="x", padx=10, pady=8)

        # Label (Bigger: 10 -> 12)
        ctk.CTkLabel(row, text=label, font=("Roboto", 12, "bold"), text_color=COLOR_TEXT_DIM).pack(side="left")

        # Value (Bigger: 11 -> 14)
        val_lbl = ctk.CTkLabel(row, text=value, font=("Roboto Mono", 14), text_color="white")
        val_lbl.pack(side="right")
        return val_lbl

    def on_packet_select(self, event):
        selected_items = self.tree.selection()
        if not selected_items: return

        item = self.tree.item(selected_items[0])
        vals = item['values']

        if vals:
            self.insp_time.configure(text=vals[1])
            self.insp_proto.configure(text=vals[2])
            self.insp_src.configure(text=vals[3])
            self.insp_dst.configure(text=vals[4])
            self.insp_len.configure(text=f"{vals[5]} bytes")

            sport = vals[6]
            dport = vals[7]
            self.insp_port.configure(text=f"{sport} → {dport}")

            s_country, s_iso, s_flag = self.analyzer.get_geoip(vals[3])
            self.insp_src_country.configure(text=f"{s_flag} {s_country}")

            d_country, d_iso, d_flag = self.analyzer.get_geoip(vals[4])
            self.insp_dst_country.configure(text=f"{d_flag} {d_country}")

            info_msg = "✔ Standard Traffic Flow"
            info_color = "#2ecc71"

            if dport == 53 or sport == 53:
                info_msg = "ℹ DNS TRAFFIC\nResolving Domain Names."
                info_color = "#3498db"
            elif dport == 443 or sport == 443:
                info_msg = "🔒 HTTPS / TLS\nEncrypted web traffic."
                info_color = "#9b59b6"
            elif dport == 80 or sport == 80:
                info_msg = "⚠ HTTP TRAFFIC\nUnencrypted web traffic. Data is visible."
                info_color = "#e67e22"
            elif vals[2] == "ARP":
                info_msg = "ℹ ARP DISCOVERY\nDevice broadcasting to map IP to MAC address."
                info_color = "#f1c40f"
            elif vals[2] == "ICMP":
                info_msg = "ℹ PING / DIAGNOSTIC\nNetwork reachability check."
                info_color = "#3498db"
            elif vals[5] > 1400:
                info_msg = "ℹ HIGH BANDWIDTH\nLarge packet size. Likely video streaming or file transfer."
                info_color = "#e74c3c"
            elif d_iso not in ["IL", "US", "LAN", "--"] and d_iso != "Unknown":
                info_msg = f"⚠ FOREIGN TRAFFIC\nConnection to {d_country} detected."
                info_color = "#e67e22"

            self.insp_status.configure(text=info_msg, text_color=info_color)

    def setup_stats_bar(self):
        self.stats_frame.grid_columnconfigure(0, weight=1)
        self.stats_frame.grid_columnconfigure(1, weight=1)
        self.stats_frame.grid_columnconfigure(2, weight=1)
        self.stats_frame.grid_columnconfigure(3, weight=1)

        self.card1, self.val_packets = self.create_stat_card(self.stats_frame, "Total Packets", "0")
        self.card1.grid(row=0, column=0, sticky="ew", padx=(0, 10))
        self.card2, self.val_flows = self.create_stat_card(self.stats_frame, "Active Flows", "0")
        self.card2.grid(row=0, column=1, sticky="ew", padx=10)
        self.card3, self.val_threats = self.create_stat_card(self.stats_frame, "Top Protocol", "---")
        self.card3.grid(row=0, column=2, sticky="ew", padx=10)
        self.card4, self.val_status = self.create_stat_card(self.stats_frame, "System Status", "IDLE")
        self.card4.grid(row=0, column=3, sticky="ew", padx=(10, 0))
        self.val_status.configure(text_color=COLOR_TEXT_DIM)

    def create_stat_card(self, parent, title, initial_value):
        card = ctk.CTkFrame(parent, fg_color=COLOR_PANEL, corner_radius=8, border_width=1, border_color="#333")
        ctk.CTkLabel(card, text=title.upper(), font=("Roboto", 10, "bold"), text_color=COLOR_TEXT_DIM).pack(padx=15,
                                                                                                            pady=(10,
                                                                                                                  0),
                                                                                                            anchor="w")
        lbl_value = ctk.CTkLabel(card, text=initial_value, font=("Roboto", 24, "bold"), text_color=COLOR_TEXT_MAIN)
        lbl_value.pack(padx=15, pady=(0, 10), anchor="w")
        return card, lbl_value

    def setup_graphs(self):
        plt.style.use('dark_background')
        self.fig, (self.ax1, self.ax2) = plt.subplots(1, 2, figsize=(10, 3.5))
        self.fig.patch.set_facecolor(COLOR_PANEL)
        self.canvas = FigureCanvasTkAgg(self.fig, master=self.graph_frame)
        self.canvas.get_tk_widget().pack(fill="both", expand=True, padx=10, pady=10)
        self.ax1.axis('off');
        self.ax2.axis('off')

    def setup_table(self):
        cols = ("#", "Time", "Proto", "Source", "Destination", "Len", "Sport", "Dport")
        self.tree = ttk.Treeview(self.list_frame, columns=cols,
                                 displaycolumns=("#", "Time", "Proto", "Source", "Destination", "Len"), show="headings",
                                 height=10)

        style = ttk.Style()
        style.theme_use("clam")
        style.configure("Treeview", background=COLOR_PANEL, foreground="white", fieldbackground=COLOR_PANEL,
                        rowheight=30, borderwidth=0, font=("Roboto", 10))
        style.configure("Treeview.Heading", background="#2b2b2b", foreground=COLOR_TEXT_DIM, relief="flat",
                        font=("Roboto", 10, "bold"))
        style.map("Treeview", background=[('selected', COLOR_ACCENT)])

        self.tree.column("#", width=60, anchor="center")
        self.tree.column("Time", width=100, anchor="center")
        self.tree.column("Proto", width=80, anchor="center")
        self.tree.column("Source", width=150, anchor="center")
        self.tree.column("Destination", width=150, anchor="center")
        self.tree.column("Len", width=80, anchor="center")
        for c in ["#", "Time", "Proto", "Source", "Destination", "Len"]:
            self.tree.heading(c, text=c)

        self.tree.bind("<<TreeviewSelect>>", self.on_packet_select)
        sb = ctk.CTkScrollbar(self.list_frame, command=self.tree.yview)
        self.tree.configure(yscrollcommand=sb.set)
        self.tree.pack(side="left", fill="both", expand=True, padx=(10, 0), pady=10)
        sb.pack(side="right", fill="y", padx=10, pady=10)

    def start_system(self):
        self.btn_start.configure(state="disabled")
        self.btn_stop.configure(state="normal")
        self.lbl_status.configure(text="● ACTIVE MONITORING", text_color="#2ecc71")
        self.val_status.configure(text="ONLINE", text_color="#2ecc71")
        for i in self.tree.get_children(): self.tree.delete(i)
        self.sniffer.start()

    def stop_system(self):
        self.sniffer.stop()
        self.btn_start.configure(state="normal")
        self.btn_stop.configure(state="disabled")
        self.lbl_status.configure(text="● PAUSED", text_color="#e74c3c")
        self.val_status.configure(text="OFFLINE", text_color="#e74c3c")

    def update_loop(self):
        if not self.running: return

        items_to_add = []
        try:
            for _ in range(50):
                if self.queue.empty(): break
                items_to_add.append(self.queue.get_nowait())
        except:
            pass

        if items_to_add:
            self.val_packets.configure(text=f"{items_to_add[-1][0]:,}")
            for item in items_to_add:
                row_string = f"{item[1]} {item[2]} {item[3]} {item[4]} {item[6]} {item[7]}".lower()
                if self.filter_text in row_string:
                    self.tree.insert("", "end", values=item)
            self.tree.yview_moveto(1)

        current_rows = self.tree.get_children()
        if len(current_rows) > 500:
            for i in current_rows[:100]: self.tree.delete(i)

        if self.queue.qsize() > 2000:
            with self.queue.mutex: self.queue.queue.clear()

        try:
            if self.sniffer.sniffing and int(time.time()) % 2 == 0:
                self.refresh_analysis()
        except:
            pass

        if self.running:
            try:
                self.after(50, self.update_loop)
            except:
                pass

    def refresh_analysis(self):
        flow_count = len(self.sniffer.flows)
        self.val_flows.configure(text=str(flow_count))
        active_flows = [f for f in self.sniffer.flows.values() if time.time() - f['last_seen'] < 30]

        if active_flows:
            df = self.analyzer.analyze_flows(active_flows)
            if not df.empty and 'protocol' in df.columns:
                try:
                    top_proto = df['protocol'].mode()[0]
                    proto_map = {6: "TCP", 17: "UDP", 1: "ICMP", 2054: "ARP"}
                    self.val_threats.configure(text=proto_map.get(top_proto, str(top_proto)))
                except:
                    pass

            self.ax1.clear();
            self.ax2.clear()
            colors = ['#3498db', '#e74c3c', '#2ecc71', '#f1c40f', '#9b59b6']
            if 'PREDICTED_CLASS' in df.columns:
                v = df.groupby('PREDICTED_CLASS')['fwd_bytes'].sum()
                if v.sum() > 0:
                    self.ax1.pie(v, labels=v.index, autopct='%1.1f%%', colors=colors,
                                 textprops={'color': "w", 'fontsize': 10}, radius=1.2)
                    self.ax1.set_title("Bandwidth Usage", color=COLOR_TEXT_DIM, fontsize=12)
                c = df['PREDICTED_CLASS'].value_counts()
                if c.sum() > 0:
                    self.ax2.pie(c, labels=c.index, autopct='%1.1f%%', colors=colors,
                                 textprops={'color': "w", 'fontsize': 10}, radius=1.2)
                    self.ax2.set_title("Active Connections", color=COLOR_TEXT_DIM, fontsize=12)
            self.canvas.draw()

    def export_data(self):
        if not self.sniffer.flows:
            messagebox.showinfo("Error", "No data to export!")
            return

        file_path = filedialog.asksaveasfilename(defaultextension=".pdf", filetypes=[("PDF Report", "*.pdf")])
        if not file_path: return

        self.fig.savefig("temp_chart.png", facecolor=COLOR_PANEL)

        pdf = PDFReport()
        pdf.add_page()

        pdf.set_font("Arial", size=12)
        pdf.cell(200, 10, txt=f"Date: {time.strftime('%Y-%m-%d %H:%M:%S')}", ln=1, align='C')
        pdf.ln(10)

        pdf.image("temp_chart.png", x=10, w=190)
        pdf.ln(10)

        pdf.set_font("Arial", 'B', 14)
        pdf.cell(200, 10, txt="Top Active Connections", ln=1, align='L')

        df = self.analyzer.analyze_flows(list(self.sniffer.flows.values()))
        if not df.empty:
            # Table Header
            pdf.set_font("Arial", 'B', 10)
            pdf.cell(50, 10, "Source IP", 1)
            pdf.cell(50, 10, "Dest IP", 1)
            pdf.cell(40, 10, "Type", 1)
            pdf.cell(30, 10, "Size (KB)", 1)
            pdf.ln()

            pdf.set_font("Arial", size=10)
            top_flows = df.sort_values(by='fwd_bytes', ascending=False).head(15)

            for index, row in top_flows.iterrows():
                src = row.get('src_ip', 'Unknown')
                dst = row.get('dst_ip', 'Unknown')
                t_type = row.get('PREDICTED_CLASS', 'Other')
                t_vol = f"{row.get('fwd_bytes', 0) / 1024:.1f}"

                pdf.cell(50, 10, str(src), 1)
                pdf.cell(50, 10, str(dst), 1)
                pdf.cell(40, 10, str(t_type), 1)
                pdf.cell(30, 10, t_vol, 1)
                pdf.ln()

        try:
            pdf.output(file_path)
            messagebox.showinfo("Success", "Full Report Generated Successfully!")
        except Exception as e:
            messagebox.showerror("Error", f"Could not save PDF:\n{e}")

        if os.path.exists("temp_chart.png"):
            os.remove("temp_chart.png")

    def on_close(self):
        self.running = False
        self.sniffer.stop()
        try:
            self.quit()
        except:
            pass